import type { Metadata } from "next";
import "./globals.css";
import Banner from "./banner/banner";
import Footer from "./footer/footer";
import Navigation from "./navigation/navigation";

export const metadata: Metadata = {
  title: "Golf Stats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <Banner headerText="Golf Stats" />
          <Navigation />
        </header>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
